### ISSUE TITLE
Example 4 help needed

### ISSUE THREAD

**Issue by Gamezpedia** [MatthijsKamstra/haxephp#3]
Hi, 

i just followed : https://matthijskamstra.github.io/haxephp/04webapi/example.html

and compiled it successfully however i am getting : 

![image](https://user-images.githubusercontent.com/1169093/32785384-360e3524-c973-11e7-8331-3f9ddf677806.png)

The problem is that i am not using root of the Localhost: i have a folder : TESST/
and the url is always going to the root [ localhost/contact ] instead of [ localhost/TESST/contact ]

i tried to add that to :            
`Dispatch.run("TESST/"+_webURI, Web.getParams(), new Routes());     `

but no matter what it is going to the root.

**Comment by MatthijsKamstra** [comment]
Hi @Gamezpedia,

thx for taking the time to follow the Haxe php instructions.

The example is a very simple one if you want to create more routes you should check out this gist https://gist.github.com/jasononeil/5667079

it might help you on your way

**Comment by MatthijsKamstra** [comment]
Oh for I forget 

I don't use the Haxe target PHP any more. So the documentation might become more and more obsolete.

I know that the new Haxe (4) version only supports php7. 

Read more about that here: https://haxe.org/download/version/4.0.0-preview.2/ 

That page also explains that the dispatch (in Haxe 4) is moving to an other lib: https://github.com/HaxeFoundation/hx3compat/tree/master/std/haxe/web

So that changes as well with the new version

**Comment by Gamezpedia** [comment]
ohh i see , it looks like i am late to the party :D any ways thanks for these tutorials i am not a php guy but they are a kick starter for me instead of writing ugly php i wrote Haxe :D   👍
